### ISSUE TITLE
Exe reporting Fatal Error

### ISSUE THREAD

**Issue by Zero-Starlight** [CensoredUsername/Nier-Automata-editor#2]
As it says on the tin, no matter where I put the N_A_editor.exe file, the app refuses to run. Am I supposed to put it somewhere specific?

**Comment by CensoredUsername** [comment]
It is supposed to be able to run anywhere. Could you run the exe from command line and report what error it gives? And what windows version you're using?

**Comment by Zero-Starlight** [comment]
Doesn't give me an error in the command prompt, I just get a Fatal Error that says: Failed to execute script N_A_Editor

I'm on 64 Bit Windows 10 version 1607. I installed the latest version of Python as well hoping that it would work but running the Python file just opens a command line for a second. :(

**Comment by Zero-Starlight** [comment]
Oh, hold on, just tried running the PY file through the command prompt and got this. Maybe this'll help?

e:\Documents\My Games\NieR_Automata>N_A_editor.py
Traceback (most recent call last):
  File "E:\Documents\My Games\NieR_Automata\N_A_editor.py", line 196, in <module>
    main()
  File "E:\Documents\My Games\NieR_Automata\N_A_editor.py", line 171, in main
    raise Exception("Could not find NieR;Automata's save folder location")
Exception: Could not find NieR;Automata's save folder location

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Documents\My Games\NieR_Automata\N_A_editor.py", line 198, in <module>
    messagebox.showerror("Whoops", "\n".join(e.args))
NameError: name 'e' is not defined

**Comment by CensoredUsername** [comment]
Hmm, looks like it couldn't find your Nier;Automata save folder and there's a bug in the code for reporting the error. I've fix that, but in the mean time, could you tell me where your folder's save location is if it isn't at "%USERPROFILE%\Documents\My Games\NieR_Automata".

**Comment by Zero-Starlight** [comment]
See, that's the thing. It _is_ located there. I've moved my documents folder over from my SSD to my HDD however, hence the E drive instead of C drive.

**Comment by CensoredUsername** [comment]
Ah yes, that's one of Windows oddities. Basically, because in earlier windows versions symlinks weren't a thing so to allow the user to move their user folder they added a hack where certain "special" folders still appear to be in the %USERPROFILE% folder while they're not actually in there. Unfortunately, this hack is not really well done, and the normal filesystem APIs do not actually treat those folders that way. You can observe this yourself, just open explorer and compare what it shows for opening just your user folder and opening C:/users/<username>. The second will not actually show the special folders. This hack is also the reason for why you can have two different "Documents" folders shown in explorer.

I think the best way to deal with this is just to prompt the user if it can't find the folder instead of erroring out. I'll try to add that.

**Comment by CensoredUsername** [comment]
It should be added now, could you see if it fixes your problem?

**Comment by Zero-Starlight** [comment]
Works perfectly now :+1: Thanks!
